{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:yetiforce:yetiforce_customer_relationship_management:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/yetiforcecompany/yetiforcecrm/commit/54728becfdad9b6e686bbe336007cba2ce518248",
        "version_end_excluding": {
            "yetiforce:yetiforce_customer_relationship_management": "6.4.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "UNKNOWN",
    "licences": {
        "database": "",
        "affected_repository": "Other"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-3002"
        ],
        "CWE": [
            "CWE-79"
        ]
    }
}