{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:jupyter:jupyter_server:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/jupyter-server/jupyter_server/commit/87a4927272819f0b1cae1afa4c8c86ee2da002fd",
        "version_end_excluding": {
            "jupyter:jupyter_server": "2.7.2"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "BSD 3-Clause \"New\" or \"Revised\" License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2023-40170"
        ],
        "CWE": [
            "CWE-284",
            "CWE-306"
        ]
    }
}