{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:pysaml2_project:pysaml2:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/IdentityPython/pysaml2/commit/1d8fd268f5bf887480a403a7a5ef8f048157cc14",
        "version_end_excluding": {
            "pysaml2_project:pysaml2": "6.5.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Apache License 2.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2021-21238"
        ],
        "CWE": [
            "CWE-347"
        ]
    }
}