{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:megacord:megabot:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/NicPWNs/MEGABOT/commit/71e79e5581ea36313700385b112d863053fb7ed6",
        "version_end_excluding": {
            "megacord:megabot": "1.5.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Unknown"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2024-43404"
        ],
        "CWE": [
            "CWE-95"
        ]
    }
}