{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:mage:mage-ai:*:*:*:*:*:python:*:*"
        ],
        "fix_commit": "https://github.com/mage-ai/mage-ai/commit/f63cd00f6a3be372397d37a4c9a49bfaf50d7650",
        "version_end_excluding": {
            "mage:mage-ai": "0.8.72"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "Apache License 2.0"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2023-31143"
        ],
        "CWE": [
            "CWE-306"
        ]
    }
}