{
    "original_source": {
        "database(url)": "https://www.cve.org",
        "software_system(CPE)": [
            "cpe:2.3:a:django-mfa3_project:django-mfa3:*:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/xi/django-mfa3/commit/32f656e22df120b84bdf010e014bb19bd97971de",
        "version_end_excluding": {
            "django-mfa3_project:django-mfa3": "0.5.0"
        },
        "path": {
            "file_path": ""
        }
    },
    "programming_language": "PYTHON",
    "licences": {
        "database": "",
        "affected_repository": "MIT License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2022-24857"
        ],
        "CWE": [
            "CWE-287"
        ]
    }
}