{
    "original_source": {
        "database(url)": "https://github.com/secureIT-project/CVEfixes",
        "software_system(CPE)": [
            "cpe:2.3:a:mlalchemy_project:mlalchemy:0.1.1:*:*:*:*:*:*:*",
            "cpe:2.3:a:mlalchemy_project:mlalchemy:0.1.2:*:*:*:*:*:*:*",
            "cpe:2.3:a:mlalchemy_project:mlalchemy:0.1.3:*:*:*:*:*:*:*",
            "cpe:2.3:a:mlalchemy_project:mlalchemy:0.2.0:*:*:*:*:*:*:*",
            "cpe:2.3:a:mlalchemy_project:mlalchemy:0.2.1:*:*:*:*:*:*:*"
        ],
        "fix_commit": "https://github.com/thanethomson/MLAlchemy/commit/bc795757febdcce430d89f9d08f75c32d6989d3c",
        "version_end_excluding": {
            "mlalchemy_project:mlalchemy": "unknown"
        },
        "path": {
            "file_path": "mlalchemy/parser.py"
        }
    },
    "programming_language": "python",
    "licences": {
        "database": "MIT",
        "affected_repository": "MIT License"
    },
    "related_vulnerability_entry": {
        "CVE": [
            "CVE-2017-16615"
        ],
        "CWE": [
            "NVD-CWE-noinfo"
        ]
    }
}